### ISSUE TITLE
Intermittent Jekyll Error After Updating to Ruby 2.7.5

### ISSUE THREAD

**Issue by idmken** [18F/federalist-uswds-jekyll#237]
I recently updated our [site](https://github.com/GSA/ficam-playbooks) from Ruby 2.6.6 to Ruby 2.7.5 after I noticed 2.6.6 is security end of life 3/31/22. Our site is based on this repo. After making the upgrade, I noticed these intermittent errors and wondered if anyone else who used this template has noticed. It seems like the first build gets the below error, but if you rebuild the same branch it goes away.

Our layouts/base.html is the same as the one in this repo. Wondering if anyone else has noticed this or resolved it.

2022-02-09 16:28:03 INFO [build-jekyll] on line 152 of /tmp/work/site_repo/node_modules/uswds/dist/scss/core/_notifications.scss
2022-02-09 16:28:03 INFO [build-jekyll] from line 21 of /tmp/work/site_repo/node_modules/uswds/dist/scss/packages/_required.scss
2022-02-09 16:28:03 INFO [build-jekyll] from line 5 of /tmp/work/site_repo/node_modules/uswds/dist/scss/uswds.scss
2022-02-09 16:28:03 INFO [build-jekyll] from line 3 of /tmp/work/site_repo/_assets/css/index.scss
**2022-02-09 16:28:04 INFO [build-jekyll] [31m  Liquid Exception: String can't be coerced into Integer in /_layouts/base.html[0m
2022-02-09 16:28:04 INFO [build-jekyll] jekyll 3.9.1 | Error:  String can't be coerced into Integer
2022-02-09 16:28:04 INFO [build-jekyll] /usr/local/rvm/gems/ruby-2.7.5/gems/sass-3.7.4/lib/sass/script/value/number.rb:409:in `-': String can't be coerced into Integer (TypeError)**
2022-02-09 16:28:04 INFO [build-jekyll] from /usr/local/rvm/gems/ruby-2.7.5/gems/sass-3.7.4/lib/sass/script/value/number.rb:409:in `basically_equal?'
2022-02-09 16:28:04 INFO [build-jekyll] from /usr/local/rvm/gems/ruby-2.7.5/gems/sass-3.7.4/lib/sass/script/value/number.rb:403:in `basically_equal?'
2022-02-09 16:28:04 INFO [build-jekyll] from /usr/local/rvm/gems/ruby-2.7.5/gems/sass-3.7.4/lib/sass/script/value/number.rb:226:in `eql?'
2022-02-09 16:28:04 INFO [build-jekyll] from /usr/local/rvm/gems/ruby-2.7.5/gems/sass-3.7.4/lib/sass/script/functions.rb:2337:in `has_key?'
2022-02-09 16:28:04 INFO [build-jekyll] from /usr/local/rvm/gems/ruby-2.7.5/gems/sass-3.7.4/lib/sass/script/functions.rb:2337:in `map_has_key'
2022-02-09 16:28:04 INFO [build-jekyll] from /usr/local/rvm/gems/ruby-2.7.5/gems/sass-3.7.4/lib/sass/script/tree/funcall.rb:151:in `block in _perform'
2022-02-09 16:28:04 INFO [build-jekyll] from /usr/local/rvm/gems/ruby-2.7.5/gems/sass-3.7.4/lib/sass/stack.rb:108:in `block in with_function'
2022-02-09 16:28:04 INFO [build-jekyll] from /usr/local/rvm/gems/ruby-2.7.5/gems/sass-3.7.4/lib/sass/stack.rb:135:in `with_frame'
2022-02-09 16:28:04 INFO [build-jekyll] from /usr/local/rvm/gems/ruby-2.7.5/gems/sass-3.7.4/lib/sass/stack.rb:108:in `with_function'
2022-02-09 16:28:04 INFO [build-jekyll] from /usr/local/rvm/gems/ruby-2.7.5/gems/sass-3.7.4/lib/sass/script/tree/funcall.rb:149:in `_perform'
2022-02-09 16:28:04 INFO [build-jekyll] from /usr/local/rvm/gems/ruby-2.7.5/gems/sass-3.7.4/lib/sass/script/tree/node.rb:50:in `perform'
2022-02-09 16:28:04 INFO [build-jekyll] from /usr/local/rvm/gems/ruby-2.7.5/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:296:in `visit_if'
2022-02-09 16:28:04 ERROR [main] There was a problem running Jekyll, see the above logs for details.

**Comment by idmken** [comment]
digging into this deeper it seems like something related to sass gem. Sass gem is deprecated and no longer supported recommended to move to sassc. Jekyll <4 still supports sass. To move to jekyll >4 need to find an alternative jekyll-assets gem because the one referenced isn't supported in jekyll>4. @michaelhortongsa @drewnielson

**Comment by svenaas** [comment]
I'm not certain this is distinct from #223
